name: Build Electron App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build macOS app
        run: npm run dist:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: release/
